server:
  port: 8003
spring:
  application:
    name: lsw-auth
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    register-with-eureka: true
    fetch-registry: true
pubKeyPath: /Users/daadreeam/Desktop/rsa.pub
privKeyPath: /Users/daadreeam/Desktop/rsa.pri
