server:
  port: 8009
spring:
  zipkin:
    base-url: http://47.93.198.65:9411
    sender:
      type: web
  sleuth:
    sampler:
      #      percentage: 1.0 !!!!!! !!
      probability: 1.0
  application:
    name: lsw-main-service
  rabbitmq:
    host: 47.93.198.65
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
# 需要配置feign的超时时间 不然默认被ribbon覆盖 两个时间都是1s
feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时
        readTimeout: 10000    #读取超时
  hystrix:
    enabled: true


