server:
  port: 8002
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: lsw-gateway
  main:
    allow-bean-definition-overriding: true #允许bean重复注册
  zipkin:
    base-url: http://47.93.198.65:9411
    sender:
      type: web
  sleuth:
    sampler:
#      percentage: 1.0 !!!!!! !!
      probability: 1.0
zuul:
#  ignored-services: microservice-provider-user,microservice-consumer-movie
#  ignored-services: lsw-zipkin-server,lsw-msg,lsw-main-service # 多服务用,间隔
  prefix: /api
  routes:
    auth:
      path: /lsw-auth-path/**
      service-id: lsw-auth
    msg:
      path: /lsw-msg-path/**
      service-id: lsw-msg
    main:
      path: /lsw-main-service-path/**
      service-id: lsw-main-service
    zipkin:
      path: /lsw-zipkin-path
      service-id: lsw-zipkin-server
myFilter:
  path:
    token: /auth/token
    login: /auth/login
    logout: /auth/logout
ribbon:
  eager-load: # ribbon饥饿加载
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
# 需要配置feign的超时时间 不然默认被ribbon覆盖 两个时间都是1s
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 10000 #连接超时
#        readTimeout: 10000    #读取超时
#    host:
#      connect-timeout-millis: 3000
#      socket-timeout-millis: 3000
#ribbon:
#  ReadTimeout: 3000
#  ConnectTimeout: 3000
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeout-in-milliseconds: 3000
#feign:
#  hystrix:
#    enabled: true
#  ribbon:
#    ReadTimeout: 5000
#    SocketTimeout: 5000



