server:
  port: 8011
spring:
  redis:
    port: 6379
    host: 47.93.198.65
    password: lsw
    database: 3
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 47.93.198.65:9300
